{
    "default": {
        "programmableStringProperties": [
            "fromCharCode",
            "fromCodePoint",
            "charAt",
            "charCodeAt",
            "codePointAt",
            "concat",
            "contains",
            "endsWith",
            "indexOf",
            "lastIndexOf",
            "localeCompare",
            "match",
            "repeat",
            "replace",
            "search",
            "slice",
            "split",
            "startsWith",
            "substr",
            "substring",
            "toLocaleLowerCase",
            "toLocaleUpperCase",
            "toLowerCase",
            "toString",
            "toUpperCase",
            "trim",
            "valueOf"
        ]
    },
    "type": "object",
    "additionalProperties": false,
    "id": "__base__",
    "properties": {
        "programmableStringProperties": {
            "type": "array",
            "items": {
                "description": "Name of String functions/properties which should be documented for Programmable Methods",
                "enum": [
                    "fromCharCode",
                    "fromCodePoint",
                    "link",
                    "anchor",
                    "big",
                    "bold",
                    "charAt",
                    "charCodeAt",
                    "codePointAt",
                    "concat",
                    "contains",
                    "endsWith",
                    "fixed",
                    "fontcolor",
                    "fontsize",
                    "indexOf",
                    "italics",
                    "lastIndexOf",
                    "localeCompare",
                    "match",
                    "repeat",
                    "replace",
                    "search",
                    "slice",
                    "small",
                    "split",
                    "startsWith",
                    "strike",
                    "sub",
                    "substr",
                    "substring",
                    "sup",
                    "toLocaleLowerCase",
                    "toLocaleUpperCase",
                    "toLowerCase",
                    "toString",
                    "toUpperCase",
                    "trim",
                    "valueOf"
                ],
                "type": "string"
            },
            "default": [
                "fromCharCode",
                "fromCodePoint",
                "charAt",
                "charCodeAt",
                "codePointAt",
                "concat",
                "contains",
                "endsWith",
                "indexOf",
                "lastIndexOf",
                "localeCompare",
                "match",
                "repeat",
                "replace",
                "search",
                "slice",
                "split",
                "startsWith",
                "substr",
                "substring",
                "toLocaleLowerCase",
                "toLocaleUpperCase",
                "toLowerCase",
                "toString",
                "toUpperCase",
                "trim",
                "valueOf"
            ]
        }
    }
}